### ISSUE TITLE
cv2.error: OpenCV(3.4.3)

### ISSUE THREAD

**Issue by yasersakkaf** [log0/video_streaming_with_flask_example#7]
I am getting this error when I try to run this code. I know the error is related to Open CV but can't understand what the error actually is:

Here the code and the error:

>>> import cv2
>>> video = cv2.VideoCapture('video.mp4')
>>> success, image = video.read()
>>> ret, jpeg = cv2.imencode('.jpg', image)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
cv2.error: OpenCV(3.4.3) /home/conda/feedstock_root/build_artifacts/opencv_1537056344807/work/modules/imgcodecs/src/grfmt_base.cpp:145: error: (-10:Unknown error code -10) Raw image encoder error: Empty JPEG image (DNL not supported) in function 'throwOnEror'

**Comment by yasersakkaf** [comment]
>>> import cv2
>>> video = cv2.VideoCapture('video.mp4')
>>> success, image = video.read()
>>> ret, jpeg = cv2.imencode('.jpg', image)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
cv2.error: OpenCV(3.4.3) /home/conda/feedstock_root/build_artifacts/opencv_1537056344807/work/modules/imgcodecs/src/grfmt_base.cpp:145: error: (-10:Unknown error code -10) Raw image encoder error: Empty JPEG image (DNL not supported) in function 'throwOnEror'

**Comment by rjunior8** [comment]
The same here. Did you solved?

**Comment by yasersakkaf** [comment]
I used OpenCV version '4.1.0' and it works for me.
What version of OpenCV are you using?

**Comment by rjunior8** [comment]
opencv-python==4.1.0.25

**Comment by rjunior8** [comment]
I solved. I executed it in debian and it worked. But it's playing slow. And when I make two connections (2 browsers), I got this: 

error while decoding MB 73 15, bytestream 5111
left block unavailable for requested intra mode
error while decoding MB 0 16, bytestream 5097

and then the app stops.
